"""G検定シラバスに基づく初期問題データ。

これらは JDLA の公式過去問ではなく、シラバスを網羅するために独自に作成した
オリジナル問題です。実際の試験での正確性は保証されません。

answer 形式:
- single: 正解選択肢の 0-based index (int)
- multi:  正解選択肢の 0-based index 配列 (list[int])
- true_false: 真偽 (bool)
- fill_blank: 正解文字列 (str)
"""

from __future__ import annotations

from typing import Any, TypedDict


class SeedQuestion(TypedDict, total=False):
    syllabus_category: str
    subcategory: str
    question_text: str
    question_type: str
    choices: list[str]
    correct_answer: Any
    explanation: str
    difficulty: int
    tags: list[str]


SEED_SOURCE = "JDLA G検定 シラバス準拠オリジナル問題 (シード v1)"


QUESTIONS: list[SeedQuestion] = [
    # ========== 機械学習の基礎 / AI概論 ==========
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "AI概論",
        "question_text": "1956年に開催され「人工知能 (Artificial Intelligence)」という言葉が初めて使われたとされる会議の名称はどれか。",
        "question_type": "single",
        "choices": ["ダートマス会議", "チューリング会議", "ジュネーブ会議", "ボストン会議"],
        "correct_answer": 0,
        "explanation": "1956年、米ダートマス大学でジョン・マッカーシーらが主催した会議。マービン・ミンスキー、クロード・シャノンらが参加し、AI という用語が初めて公式に使われた。",
        "difficulty": 1,
        "tags": ["AI概論", "歴史"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "AI概論",
        "question_text": "アラン・チューリングが提案した、機械が人間と区別がつかない応答ができれば知能を持つとみなすテストの名称はどれか。",
        "question_type": "single",
        "choices": ["チューリングテスト", "ローブナーテスト", "イライザテスト", "シーボーグテスト"],
        "correct_answer": 0,
        "explanation": "1950年の論文「Computing Machinery and Intelligence」で提案された判別テスト。模倣ゲーム (Imitation Game) とも呼ばれる。",
        "difficulty": 1,
        "tags": ["AI概論", "チューリングテスト"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "AI概論",
        "question_text": "AI ブームと中心技術の組み合わせとして正しいものをすべて選べ。",
        "question_type": "multi",
        "choices": [
            "第1次 AI ブーム — 探索・推論",
            "第2次 AI ブーム — エキスパートシステム",
            "第3次 AI ブーム — ディープラーニング",
            "第2次 AI ブーム — Transformer",
        ],
        "correct_answer": [0, 1, 2],
        "explanation": "Transformer は2017年提案で第3次 AI ブームの代表技術。第2次は1980年代のエキスパートシステム (MYCIN等)、第1次は1950-60年代の探索・推論。",
        "difficulty": 2,
        "tags": ["AI概論", "歴史"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "AI概論",
        "question_text": "レイ・カーツワイルが提唱したシンギュラリティ (技術的特異点) の到来予測年として最も適切なものはどれか。",
        "question_type": "single",
        "choices": ["2025年", "2035年", "2045年", "2100年"],
        "correct_answer": 2,
        "explanation": "著書『The Singularity Is Near』(2005) でレイ・カーツワイルは2045年にシンギュラリティが到来すると予測した。",
        "difficulty": 1,
        "tags": ["AI概論", "シンギュラリティ"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "AI概論",
        "question_text": "「フレーム問題」とは、AI が現実世界で行動を選択する際に、関連する事柄を絞り込めずに無限の検討を要してしまう問題のことである。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "1969年マッカーシーとヘイズが指摘した AI の根本問題の一つ。現実世界では考慮すべき要素が無限にあり、AI は「何が関係し何が無関係か」を効率的に判定できない。",
        "difficulty": 2,
        "tags": ["AI概論", "フレーム問題"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "AI概論",
        "question_text": "「大人の知的作業より乳幼児の運動・知覚の方が AI には難しい」というパラドックスを唱えた人物の名前を答えよ (カタカナ)。",
        "question_type": "fill_blank",
        "choices": [],
        "correct_answer": "モラベック",
        "explanation": "ハンス・モラベック (Hans Moravec) が1980年代に提唱。チェスのような知的作業は AI でも比較的容易だが、人間が無意識に行う知覚・運動は再現が困難。",
        "difficulty": 2,
        "tags": ["AI概論", "モラベックのパラドックス"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "AI概論",
        "question_text": "ジョン・サールが提示した「中国語の部屋」の思考実験が主張する内容として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "シンボル操作だけでは真の意味理解は生まれない",
            "コンピュータの計算速度には物理的限界がある",
            "人間の脳は機械より優れた構造を持つ",
            "中国語は機械翻訳が最も難しい言語である",
        ],
        "correct_answer": 0,
        "explanation": "1980年論文。中の人が中国語のルールに従ってシンボル操作するだけでは中国語を「理解」しているとは言えない、と強い AI 仮説に反論した。",
        "difficulty": 2,
        "tags": ["AI概論", "中国語の部屋"],
    },
    # ========== 機械学習の基礎 / 機械学習の手法 ==========
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "機械学習の手法",
        "question_text": "次のうち、教師なし学習に分類される手法はどれか。",
        "question_type": "single",
        "choices": ["ロジスティック回帰", "k-means クラスタリング", "ランダムフォレスト", "サポートベクターマシン"],
        "correct_answer": 1,
        "explanation": "k-means はラベルなしデータをクラスタに分割する代表的な教師なし学習手法。残り3つはいずれも教師あり学習。",
        "difficulty": 1,
        "tags": ["機械学習", "教師なし学習"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "機械学習の手法",
        "question_text": "過学習 (overfitting) とは、モデルが訓練データに適合しすぎて未知データへの汎化性能が下がる現象のことである。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "過学習はバイアス・バリアンスのトレードオフでバリアンスが高い状態。正則化やドロップアウト、データ拡張などで対策する。",
        "difficulty": 1,
        "tags": ["機械学習", "過学習"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "機械学習の手法",
        "question_text": "L1 正則化 (Lasso) の特徴として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "全ての重みを一様に縮小する",
            "多くの重みを 0 にしてスパース解を得る",
            "学習率を自動調整する",
            "勾配消失を防ぐ",
        ],
        "correct_answer": 1,
        "explanation": "L1 ノルム (絶対値和) のペナルティを加えると、最適化過程で多くの重みが厳密に 0 になり特徴選択の効果が得られる。L2 (Ridge) は全体を縮小する。",
        "difficulty": 2,
        "tags": ["機械学習", "正則化", "L1"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "機械学習の手法",
        "question_text": "二値分類モデルの性能指標 AUC (Area Under the Curve) について、最も適切な説明はどれか。",
        "question_type": "single",
        "choices": [
            "適合率と再現率の調和平均",
            "正答数を全体で割った値",
            "ROC 曲線下の面積で、1 に近いほど性能が高い",
            "予測値と実測値の二乗誤差",
        ],
        "correct_answer": 2,
        "explanation": "AUC-ROC は閾値を変化させたときの真陽性率と偽陽性率の関係を曲線で表し、その下の面積を示す。閾値非依存の総合指標として広く使われる。",
        "difficulty": 2,
        "tags": ["機械学習", "評価指標", "AUC"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "機械学習の手法",
        "question_text": "k 分割交差検証 (k-fold cross validation) ではデータを k 個のサブセットに分け、k 回学習・評価を繰り返して汎化性能を推定する。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "毎回 k-1 個を学習用、残り 1 個を検証用に使い、k 回の評価値を平均する。データ全体を学習にも検証にも活用できる手法。",
        "difficulty": 1,
        "tags": ["機械学習", "交差検証"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "機械学習の手法",
        "question_text": "勾配ブースティング (Gradient Boosting) の実装として広く使われているライブラリをすべて選べ。",
        "question_type": "multi",
        "choices": ["XGBoost", "LightGBM", "CatBoost", "Word2Vec"],
        "correct_answer": [0, 1, 2],
        "explanation": "XGBoost, LightGBM, CatBoost はいずれも勾配ブースティング決定木の代表的実装。Word2Vec は単語の分散表現学習手法で別カテゴリ。",
        "difficulty": 2,
        "tags": ["機械学習", "勾配ブースティング"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "機械学習の手法",
        "question_text": "適合率 (Precision) と再現率 (Recall) の調和平均で求められる評価指標の名称を半角英数で答えよ (例: F1)。",
        "question_type": "fill_blank",
        "choices": [],
        "correct_answer": "F1",
        "explanation": "F1 値は 2PR/(P+R) で計算される調和平均。適合率と再現率のバランスを取る指標で、不均衡データの分類で重宝される。",
        "difficulty": 2,
        "tags": ["機械学習", "F1スコア"],
    },
    {
        "syllabus_category": "機械学習の基礎",
        "subcategory": "機械学習の手法",
        "question_text": "k-means クラスタリングの説明として誤っているものはどれか。",
        "question_type": "single",
        "choices": [
            "クラスタ数 k を事前に指定する必要がある",
            "クラスタ重心と各点の距離に基づきクラスタを更新する",
            "初期値によって結果が変わる場合がある",
            "教師あり学習の代表的手法である",
        ],
        "correct_answer": 3,
        "explanation": "k-means はラベルを使わない教師なし学習。クラスタ数 k の指定、初期値依存、距離ベースの反復更新が特徴。",
        "difficulty": 2,
        "tags": ["機械学習", "クラスタリング"],
    },
    # ========== ディープラーニングの基礎 / DL概要 ==========
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "DL概要",
        "question_text": "活性化関数 ReLU の出力として正しい式はどれか (入力 x に対して)。",
        "question_type": "single",
        "choices": ["max(0, x)", "1 / (1 + exp(-x))", "tanh(x)", "x²"],
        "correct_answer": 0,
        "explanation": "ReLU (Rectified Linear Unit) は max(0, x)。負の入力は 0、正は恒等。勾配消失を緩和し計算が速いため現代 DL の標準。",
        "difficulty": 1,
        "tags": ["DL", "活性化関数", "ReLU"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "DL概要",
        "question_text": "最適化アルゴリズム Adam の特徴として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "学習率を全てのパラメータで同じに保つ",
            "モメンタムと RMSProp の利点を組み合わせる",
            "勾配を全く使用しない",
            "重みの初期化のみを最適化する",
        ],
        "correct_answer": 1,
        "explanation": "Adam (Adaptive Moment Estimation) はモメンタム (1次モーメント) と RMSProp (2次モーメント) を統合した最適化手法。現在の事実上の標準。",
        "difficulty": 2,
        "tags": ["DL", "最適化", "Adam"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "DL概要",
        "question_text": "深いネットワークでシグモイド関数を使うと発生しやすい問題はどれか。",
        "question_type": "single",
        "choices": ["勾配爆発", "勾配消失", "過適合のみ", "計算量の減少"],
        "correct_answer": 1,
        "explanation": "シグモイドは入力が大きい/小さいときに勾配がほぼ 0 になるため、誤差逆伝播で勾配が連鎖的に小さくなり消失する。ReLU で緩和される。",
        "difficulty": 2,
        "tags": ["DL", "勾配消失"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "DL概要",
        "question_text": "ドロップアウトは訓練時に一部のニューロンをランダムに無効化することで過学習を抑制する技術である。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "Hinton らが2012年に提案。アンサンブル学習の効果が得られ汎化性能が向上する。推論時には全ニューロンを使い出力をスケーリングする。",
        "difficulty": 1,
        "tags": ["DL", "ドロップアウト"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "DL概要",
        "question_text": "バッチ正規化 (Batch Normalization) の主な目的として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "各層の入力分布を正規化して学習を安定化・高速化する",
            "重みを 0 で初期化する",
            "ニューロン数を自動的に増やす",
            "活性化関数を ReLU に置換する",
        ],
        "correct_answer": 0,
        "explanation": "Ioffe と Szegedy が2015年に提案。各層の入力を mini-batch ごとに平均 0、分散 1 に正規化することで内部共変量シフトを抑え、学習を安定化する。",
        "difficulty": 2,
        "tags": ["DL", "Batch Normalization"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "DL概要",
        "question_text": "誤差逆伝播法 (Backpropagation) では連鎖律を用いて出力層から入力層に向かって勾配を計算する。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "1986年 Rumelhart, Hinton, Williams が普及させた。各層の重みに関する損失の勾配を効率的に計算でき、深層学習の基礎となっている。",
        "difficulty": 1,
        "tags": ["DL", "誤差逆伝播"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "DL概要",
        "question_text": "勾配降下法で「重みをどれだけ動かすか」を制御する最重要ハイパーパラメータの名称を漢字で答えよ (例: 学習率)。",
        "question_type": "fill_blank",
        "choices": [],
        "correct_answer": "学習率",
        "explanation": "学習率 (learning rate) は最適化で重みの更新幅を決める係数。大きすぎると発散、小さすぎると収束しない。実務で最も慎重に調整するハイパーパラメータ。",
        "difficulty": 1,
        "tags": ["DL", "学習率"],
    },
    # ========== ディープラーニングの基礎 / CNN ==========
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "CNN",
        "question_text": "2012年の ILSVRC で従来手法を大差で破り、ディープラーニングの転換点となったモデルはどれか。",
        "question_type": "single",
        "choices": ["LeNet", "AlexNet", "ResNet", "EfficientNet"],
        "correct_answer": 1,
        "explanation": "AlexNet (Krizhevsky, Sutskever, Hinton) が ILSVRC2012 で誤差率を 26% から 15% に大幅改善し、深層学習革命の引き金となった。",
        "difficulty": 1,
        "tags": ["CNN", "AlexNet"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "CNN",
        "question_text": "ResNet の最大の特徴として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "Inception モジュールを採用している",
            "残差接続 (スキップ接続) により非常に深いネットワークの学習を可能にした",
            "畳み込みを使わず全結合のみで構成される",
            "活性化関数として sigmoid のみを使う",
        ],
        "correct_answer": 1,
        "explanation": "ResNet (2015, He ら) は入力を数層越しに加算する残差接続を導入し、100層以上の深層学習を可能にした。ILSVRC2015 優勝。",
        "difficulty": 2,
        "tags": ["CNN", "ResNet"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "CNN",
        "question_text": "物体検出 (Object Detection) のモデルをすべて選べ。",
        "question_type": "multi",
        "choices": ["YOLO", "Faster R-CNN", "SSD", "Word2Vec"],
        "correct_answer": [0, 1, 2],
        "explanation": "YOLO は1段階、Faster R-CNN は2段階、SSD は1段階の物体検出モデル。Word2Vec は単語の分散表現で別タスク。",
        "difficulty": 2,
        "tags": ["CNN", "物体検出"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "CNN",
        "question_text": "CNN におけるプーリング層 (Pooling Layer) の役割として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "特徴マップをダウンサンプリングして計算量を削減し位置の微小な変化に頑健にする",
            "学習率を調整する",
            "重みを正則化する",
            "活性化関数を切り替える",
        ],
        "correct_answer": 0,
        "explanation": "Max Pooling や Average Pooling で領域代表値を取り、空間方向に縮小する。位置不変性 (translation invariance) の獲得にも寄与する。",
        "difficulty": 1,
        "tags": ["CNN", "プーリング"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "CNN",
        "question_text": "U-Net が広く使われる代表的なタスクはどれか。",
        "question_type": "single",
        "choices": ["物体検出", "セマンティックセグメンテーション (特に医療画像)", "音声認識", "強化学習"],
        "correct_answer": 1,
        "explanation": "U-Net は2015年に医療画像のセグメンテーション向けに提案された。エンコーダ・デコーダ構造にスキップ接続を加えた U 字型の構造が特徴。",
        "difficulty": 2,
        "tags": ["CNN", "U-Net", "セグメンテーション"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "CNN",
        "question_text": "ゼロパディング (Zero Padding) を使うと出力特徴マップのサイズを入力と同じに保つことができる。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "入力の周囲を 0 で埋めることで畳み込み後のサイズ減少を相殺できる。'same' padding と呼ばれ、深いネットワーク構築で必須。",
        "difficulty": 1,
        "tags": ["CNN", "パディング"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "CNN",
        "question_text": "Vision Transformer (ViT) の特徴として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "畳み込み層のみで構成される",
            "画像をパッチに分割し Transformer で処理する",
            "RNN を中核に持つ",
            "強化学習でのみ学習される",
        ],
        "correct_answer": 1,
        "explanation": "ViT (2020) は画像を 16×16 などのパッチに分割し系列として扱い、Transformer Encoder で処理する。大規模事前学習で CNN を超える性能を達成した。",
        "difficulty": 2,
        "tags": ["CNN", "ViT", "Transformer"],
    },
    # ========== ディープラーニングの基礎 / RNN・自然言語処理 ==========
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "RNN・NLP",
        "question_text": "LSTM が持つゲートをすべて選べ。",
        "question_type": "multi",
        "choices": ["入力ゲート", "忘却ゲート", "出力ゲート", "リセットゲート"],
        "correct_answer": [0, 1, 2],
        "explanation": "LSTM は入力・忘却・出力の 3 ゲート + セル状態。リセットゲートは GRU のゲート。",
        "difficulty": 2,
        "tags": ["RNN", "LSTM"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "RNN・NLP",
        "question_text": "Word2Vec の学習手法に含まれるものとして最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "Skip-gram と CBOW",
            "Q学習と SARSA",
            "L1 正則化と L2 正則化",
            "Max Pooling と Average Pooling",
        ],
        "correct_answer": 0,
        "explanation": "Skip-gram は中心語から周辺語を、CBOW は周辺語から中心語を予測する。Mikolov ら (2013) が提案。",
        "difficulty": 2,
        "tags": ["NLP", "Word2Vec"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "RNN・NLP",
        "question_text": "Attention 機構の主な目的として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "活性化関数の置換",
            "系列のどこに着目すべきかを動的に学習する",
            "学習率を自動調整する",
            "勾配を完全に消失させる",
        ],
        "correct_answer": 1,
        "explanation": "Attention は入力系列の各位置に重みを付け、出力生成時に関連する位置に注目できる。Bahdanau ら2014年の論文がきっかけ。Transformer の中核技術。",
        "difficulty": 2,
        "tags": ["NLP", "Attention"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "RNN・NLP",
        "question_text": "機械翻訳の自動評価指標として代表的な BLEU は何を測るか。",
        "question_type": "single",
        "choices": [
            "n-gram の一致度",
            "文章の感情極性",
            "学習にかかる時間",
            "モデルのパラメータ数",
        ],
        "correct_answer": 0,
        "explanation": "BLEU (Bilingual Evaluation Understudy) は参照訳と機械翻訳の n-gram (主に 1~4) の一致度を見る指標。0〜1 (または0〜100) で表現される。",
        "difficulty": 1,
        "tags": ["NLP", "BLEU"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "RNN・NLP",
        "question_text": "日本語の形態素解析ツールとして代表的なものはどれか。",
        "question_type": "single",
        "choices": ["NLTK", "MeCab", "spaCy (英語版のみ)", "OpenCV"],
        "correct_answer": 1,
        "explanation": "MeCab は工藤拓らが開発した高速な日本語形態素解析ツール。Janome, Sudachi, GiNZA なども広く使われる。",
        "difficulty": 1,
        "tags": ["NLP", "形態素解析"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "RNN・NLP",
        "question_text": "Seq2Seq モデルはエンコーダで入力系列を中間表現に圧縮し、デコーダがそれをもとに出力系列を生成する。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "Sutskever ら (2014) が機械翻訳のために提案。任意長の入力系列と出力系列を扱える。Attention の追加でさらに性能向上。",
        "difficulty": 1,
        "tags": ["NLP", "Seq2Seq"],
    },
    {
        "syllabus_category": "ディープラーニングの基礎",
        "subcategory": "RNN・NLP",
        "question_text": "頻出するバイトペアを統合して語彙を作るサブワード分割手法の名称をアルファベット3文字で答えよ。",
        "question_type": "fill_blank",
        "choices": [],
        "correct_answer": "BPE",
        "explanation": "BPE (Byte Pair Encoding) は元々データ圧縮の手法で、NLP では未知語対策として GPT 系で広く使われる。WordPiece, SentencePiece も類似手法。",
        "difficulty": 2,
        "tags": ["NLP", "BPE", "サブワード"],
    },
    # ========== ディープラーニングの応用 / Transformer・LLM ==========
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "Transformer・LLM",
        "question_text": "Transformer を提案した2017年の論文タイトルとして正しいものはどれか。",
        "question_type": "single",
        "choices": [
            "Deep Residual Learning for Image Recognition",
            "Attention Is All You Need",
            "ImageNet Classification with Deep CNNs",
            "Generative Adversarial Nets",
        ],
        "correct_answer": 1,
        "explanation": "Vaswani ら2017年 NeurIPS の論文「Attention Is All You Need」で RNN を使わず Attention のみで構成する Transformer を提案。",
        "difficulty": 1,
        "tags": ["Transformer"],
    },
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "Transformer・LLM",
        "question_text": "BERT の事前学習タスクをすべて選べ。",
        "question_type": "multi",
        "choices": [
            "Masked Language Modeling (MLM)",
            "Next Sentence Prediction (NSP)",
            "Autoregressive Language Modeling",
            "Image Captioning",
        ],
        "correct_answer": [0, 1],
        "explanation": "BERT は MLM (一部トークンを隠して予測) と NSP (2文が連続するか) で事前学習。Autoregressive (次トークン予測) は GPT 系の手法。",
        "difficulty": 2,
        "tags": ["LLM", "BERT"],
    },
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "Transformer・LLM",
        "question_text": "RLHF (Reinforcement Learning from Human Feedback) の目的として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "モデルの推論速度を上げる",
            "人間の選好に沿うようにモデルを微調整する",
            "GPU メモリ使用量を削減する",
            "学習データを自動収集する",
        ],
        "correct_answer": 1,
        "explanation": "人間が複数の出力に選好を付け、報酬モデルを学習し PPO などで方策を最適化する。ChatGPT/Claude の安全性・有用性向上に貢献。",
        "difficulty": 2,
        "tags": ["LLM", "RLHF"],
    },
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "Transformer・LLM",
        "question_text": "LLM のハルシネーション (hallucination) とは、もっともらしいが事実と異なる情報を生成してしまう現象を指す。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "LLM の代表的課題。RAG (検索拡張生成)、Citation、Self-Consistency 等で軽減できるが完全な解消は難しい。",
        "difficulty": 1,
        "tags": ["LLM", "ハルシネーション"],
    },
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "Transformer・LLM",
        "question_text": "プロンプトに数個の入出力例を含めて推論させる手法を何と呼ぶか。",
        "question_type": "single",
        "choices": ["Zero-shot Learning", "Few-shot Learning", "Fine-tuning", "Pretraining"],
        "correct_answer": 1,
        "explanation": "Few-shot Learning (Few-shot Prompting / In-Context Learning) は LLM の重要能力。例 0 個なら Zero-shot、1個なら One-shot。",
        "difficulty": 2,
        "tags": ["LLM", "Few-shot"],
    },
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "Transformer・LLM",
        "question_text": "スケーリング則によれば、モデルのパラメータ数・学習データ量・計算量を増やすと損失は対数的に減少する。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "OpenAI Kaplan ら2020年の論文で示された経験則。Chinchilla 則 (DeepMind, 2022) では計算予算に対する最適な配分が示された。",
        "difficulty": 2,
        "tags": ["LLM", "スケーリング則"],
    },
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "Transformer・LLM",
        "question_text": "「ステップバイステップで考えて」とプロンプトに加えると推論精度が向上する手法の名称はどれか。",
        "question_type": "single",
        "choices": [
            "Chain-of-Thought (CoT) Prompting",
            "Adversarial Prompting",
            "Embedding Lookup",
            "Reinforcement Tuning",
        ],
        "correct_answer": 0,
        "explanation": "Wei ら (2022) が示した手法。中間推論ステップを明示することで複雑な算術・論理問題の精度が大幅向上する。",
        "difficulty": 2,
        "tags": ["LLM", "CoT"],
    },
    # ========== ディープラーニングの応用 / 生成AI ==========
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "生成AI",
        "question_text": "GAN (Generative Adversarial Network) を構成する2つのネットワークをすべて選べ。",
        "question_type": "multi",
        "choices": ["Generator (生成器)", "Discriminator (識別器)", "Encoder", "Critic Network"],
        "correct_answer": [0, 1],
        "explanation": "Goodfellow ら2014年提案。Generator が偽物を作り Discriminator が本物/偽物を判別する敵対的学習を行う。Encoder は VAE 等の部品、Critic は WGAN の Discriminator 名称。",
        "difficulty": 1,
        "tags": ["生成AI", "GAN"],
    },
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "生成AI",
        "question_text": "拡散モデル (Diffusion Model) の学習対象として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "画像を分類するモデル",
            "段階的にノイズを除去するモデル",
            "強化学習の方策",
            "RNN の隠れ状態",
        ],
        "correct_answer": 1,
        "explanation": "前向き過程で画像にノイズを加え、逆向き過程でそれを除去する U-Net を学習する。DDPM (2020) が代表的。",
        "difficulty": 2,
        "tags": ["生成AI", "拡散モデル"],
    },
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "生成AI",
        "question_text": "Stable Diffusion のベースとなっている拡散モデルの種類はどれか。",
        "question_type": "single",
        "choices": [
            "Pixel Diffusion",
            "Latent Diffusion (潜在拡散モデル)",
            "Score-based Diffusion in Frequency Domain",
            "Diffusion GAN",
        ],
        "correct_answer": 1,
        "explanation": "Stable Diffusion は VAE で圧縮した潜在空間で拡散を行う Latent Diffusion Model (Rombach ら, 2022) がベース。計算効率が劇的に向上する。",
        "difficulty": 2,
        "tags": ["生成AI", "Stable Diffusion"],
    },
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "生成AI",
        "question_text": "CLIP (Contrastive Language-Image Pre-training) は何を学習するモデルか。",
        "question_type": "single",
        "choices": [
            "画像とテキストを共通の埋め込み空間に対応付ける",
            "音声を文字起こしする",
            "画像から3D形状を生成する",
            "強化学習の方策を最適化する",
        ],
        "correct_answer": 0,
        "explanation": "OpenAI が2021年に発表。画像と説明文のペアで対照学習を行い、ゼロショット画像分類や DALL-E 系のテキスト→画像生成の基盤となる。",
        "difficulty": 2,
        "tags": ["生成AI", "CLIP"],
    },
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "生成AI",
        "question_text": "GAN の代表的な問題であるモード崩壊 (mode collapse) とは、Generator が多様な出力を作れず似たサンプルばかり生成してしまう現象である。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "GAN の学習で起きやすい問題。WGAN, Mini-batch Discrimination, スペクトル正規化等で対策する。",
        "difficulty": 2,
        "tags": ["生成AI", "GAN", "モード崩壊"],
    },
    {
        "syllabus_category": "ディープラーニングの応用",
        "subcategory": "生成AI",
        "question_text": "生成 AI を悪用した偽動画 (本人ではない人物が話している等) は「ディープフェイク」と呼ばれ社会問題化している。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "Deep Learning + Fake の造語。なりすまし、虚偽情報、選挙妨害等のリスクがあり、C2PA など出所証明の仕組みが検討されている。",
        "difficulty": 1,
        "tags": ["生成AI", "ディープフェイク", "倫理"],
    },
    # ========== AI倫理・社会実装 / 倫理 ==========
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI倫理",
        "question_text": "米国で再犯予測に用いられたが人種バイアスが指摘され大きな議論となった AI システムの名称はどれか。",
        "question_type": "single",
        "choices": ["COMPAS", "Watson", "AlphaGo", "Tay"],
        "correct_answer": 0,
        "explanation": "COMPAS は再犯リスクを予測する判決支援システム。ProPublica の2016年の調査で黒人に不利な誤判定が多いと報じられた。",
        "difficulty": 2,
        "tags": ["倫理", "バイアス", "事例"],
    },
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI倫理",
        "question_text": "シャプレー値に基づいて各特徴量の予測への寄与度を算出する XAI 手法はどれか。",
        "question_type": "single",
        "choices": ["LIME", "SHAP", "Grad-CAM", "t-SNE"],
        "correct_answer": 1,
        "explanation": "SHAP (SHapley Additive exPlanations) はゲーム理論のシャプレー値を機械学習に応用。一貫性・局所精度の理論的保証がある。",
        "difficulty": 2,
        "tags": ["XAI", "SHAP"],
    },
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI倫理",
        "question_text": "顔認識 AI が肌の色の濃い女性で誤認識率が高くなった事例の主因として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "GPU の性能不足",
            "訓練データに白人男性が偏って多かったというデータバイアス",
            "ハードウェアの故障",
            "ニューラルネットワークの深さが足りない",
        ],
        "correct_answer": 1,
        "explanation": "Buolamwini & Gebru (2018) 'Gender Shades' が報告。訓練データの偏りがそのままモデルの精度差として現れる典型事例。",
        "difficulty": 2,
        "tags": ["倫理", "バイアス", "顔認識"],
    },
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI倫理",
        "question_text": "Grad-CAM はどのような目的で使われるか。",
        "question_type": "single",
        "choices": [
            "学習率を可視化する",
            "CNN が画像のどの領域に注目して分類したかをヒートマップで可視化する",
            "GAN の生成画像を評価する",
            "RNN の隠れ状態を圧縮する",
        ],
        "correct_answer": 1,
        "explanation": "Grad-CAM (Selvaraju ら, 2017) は最後の畳み込み層の勾配を使って入力画像のどこが分類根拠かをヒートマップ化する代表的 XAI 手法。",
        "difficulty": 2,
        "tags": ["XAI", "Grad-CAM"],
    },
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI倫理",
        "question_text": "AI 公平性の定量指標として知られているものをすべて選べ。",
        "question_type": "multi",
        "choices": [
            "Demographic Parity",
            "Equal Opportunity",
            "Equalized Odds",
            "Mean Squared Error",
        ],
        "correct_answer": [0, 1, 2],
        "explanation": "MSE は回帰の誤差指標で公平性指標ではない。他の3つはグループ間で予測陽性率・真陽性率・真偽陽性率を等しくする公平性指標。",
        "difficulty": 3,
        "tags": ["倫理", "公平性指標"],
    },
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI倫理",
        "question_text": "OECD AI 原則 (2019) に含まれる項目として適切なものをすべて選べ。",
        "question_type": "multi",
        "choices": [
            "包摂的成長、持続可能な開発",
            "透明性と説明可能性",
            "堅牢性・セキュリティ・安全性",
            "AI の独占的利用を国家戦略とすること",
        ],
        "correct_answer": [0, 1, 2],
        "explanation": "OECD AI 原則は5項目: 包摂的成長/人間中心の価値/透明性と説明可能性/堅牢性とセキュリティ/説明責任。最後の選択肢は誤り。",
        "difficulty": 2,
        "tags": ["倫理", "OECD"],
    },
    # ========== AI倫理・社会実装 / 法律 ==========
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI法律",
        "question_text": "EU AI Act におけるリスク分類の階層数はいくつか。",
        "question_type": "single",
        "choices": ["2階層", "3階層", "4階層", "5階層"],
        "correct_answer": 2,
        "explanation": "EU AI Act (2024) は「許容できないリスク」「高リスク」「限定的リスク」「最小リスク」の4階層に分類する。",
        "difficulty": 2,
        "tags": ["法律", "EU AI Act"],
    },
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI法律",
        "question_text": "日本の著作権法30条の4により、情報解析目的であれば原則として著作物を学習データに利用できる (ただし権利者の利益を不当に害する場合を除く)。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "2018年改正で導入。AI 学習目的の著作物利用が広く許容されるが、3号但し書きで「権利者の利益を不当に害する場合」は除外される点に注意。",
        "difficulty": 2,
        "tags": ["法律", "著作権"],
    },
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI法律",
        "question_text": "GDPR 第22条が個人に保障する権利として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "完全に自動化された処理のみによる重要な意思決定の対象とされない権利",
            "AI 開発企業にデータを提供する義務",
            "AI 製品を無料で利用する権利",
            "アルゴリズムの完全なソースコード開示を求める権利",
        ],
        "correct_answer": 0,
        "explanation": "GDPR 第22条は自動化された意思決定 (採用、与信等) のみで重要な決定を行わないことを求め、説明を受ける権利等を保障している。",
        "difficulty": 2,
        "tags": ["法律", "GDPR"],
    },
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI法律",
        "question_text": "日本の AI 事業者ガイドライン (2024) が想定する事業者区分の数はいくつか。",
        "question_type": "single",
        "choices": ["2区分", "3区分", "4区分", "5区分"],
        "correct_answer": 1,
        "explanation": "AI 開発者、AI 提供者、AI 利用者の3区分。それぞれに共通の指針と区分別の指針が定められている。",
        "difficulty": 2,
        "tags": ["法律", "AI事業者ガイドライン"],
    },
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI法律",
        "question_text": "AI が学習データを「丸暗記」して類似性・依拠性が認められる出力を行った場合は、生成段階で著作権侵害となる可能性がある。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "学習段階は30条の4で許容されても、生成段階で既存著作物との類似性・依拠性が認められる場合は通常の著作権侵害判断が適用される。",
        "difficulty": 2,
        "tags": ["法律", "著作権", "生成段階"],
    },
    {
        "syllabus_category": "AI倫理・社会実装",
        "subcategory": "AI法律",
        "question_text": "改正個人情報保護法 (2022施行) で導入された、特定の個人を識別できないように加工した情報の名称は「仮名加工情報」である。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "仮名加工情報は他の情報と照合しなければ個人を特定できないよう加工された情報。匿名加工情報より制約が緩く、内部分析等での利用が容易。",
        "difficulty": 2,
        "tags": ["法律", "個人情報保護法"],
    },
    # ========== AI社会実装 / プロジェクト ==========
    {
        "syllabus_category": "AI社会実装",
        "subcategory": "AIプロジェクト",
        "question_text": "CRISP-DM のフェーズに含まれるものをすべて選べ。",
        "question_type": "multi",
        "choices": [
            "Business Understanding",
            "Data Preparation",
            "Modeling",
            "User Acquisition Marketing",
        ],
        "correct_answer": [0, 1, 2],
        "explanation": "CRISP-DM は6フェーズ: Business Understanding / Data Understanding / Data Preparation / Modeling / Evaluation / Deployment。マーケティング段階は含まれない。",
        "difficulty": 2,
        "tags": ["プロジェクト", "CRISP-DM"],
    },
    {
        "syllabus_category": "AI社会実装",
        "subcategory": "AIプロジェクト",
        "question_text": "AI プロジェクトで「PoC 死」と呼ばれる現象として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "PoC 段階でモデル精度が下がる",
            "PoC は成功したが本番展開されないまま終わる",
            "学習データが破損する",
            "GPU が突然壊れる",
        ],
        "correct_answer": 1,
        "explanation": "PoC で良い結果が出ても、業務適用性・運用コスト・組織課題等で本番化されず終わるケース。ビジネス価値とのギャップが主因。",
        "difficulty": 1,
        "tags": ["プロジェクト", "PoC"],
    },
    {
        "syllabus_category": "AI社会実装",
        "subcategory": "AIプロジェクト",
        "question_text": "データリーケージ (data leakage) とは、訓練データに本来知り得ないはずの未来情報や正解情報が混入し、過大な性能評価につながる事故である。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "代表例: 時系列を考慮しない CV、目的変数と相関する不適切な特徴量、テストデータが訓練データに重複等。本番投入で性能が落ちる原因となる。",
        "difficulty": 2,
        "tags": ["プロジェクト", "データリーケージ"],
    },
    {
        "syllabus_category": "AI社会実装",
        "subcategory": "AIプロジェクト",
        "question_text": "MLOps の主な目的として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "モデルの開発・展開・運用・監視・再学習をパイプライン化して継続運用する",
            "ハードウェアコストを増やす",
            "学習データを公開する",
            "モデルを必ず深層学習にする",
        ],
        "correct_answer": 0,
        "explanation": "MLOps はソフトウェアの DevOps と類似の発想で、モデルの CI/CD、バージョン管理、モニタリング、再学習を体系化する考え方・プラクティス。",
        "difficulty": 2,
        "tags": ["プロジェクト", "MLOps"],
    },
    {
        "syllabus_category": "AI社会実装",
        "subcategory": "AIプロジェクト",
        "question_text": "経済産業省「AI 開発契約モデル契約」(2018, 改訂2020) で示された段階モデルにおいて、最後の段階として位置づけられるものはどれか。",
        "question_type": "single",
        "choices": [
            "アセスメント段階",
            "PoC 段階",
            "開発段階",
            "追加学習段階",
        ],
        "correct_answer": 3,
        "explanation": "探索的段階型契約は アセスメント → PoC → 開発 → 追加学習 の4段階。各段階での権利・責任を分けて契約するモデル。",
        "difficulty": 3,
        "tags": ["プロジェクト", "契約", "経産省"],
    },
    # ========== 数学基礎 / 確率・統計 ==========
    {
        "syllabus_category": "数学基礎",
        "subcategory": "確率・統計",
        "question_text": "ベイズの定理 P(A|B) を求める式として正しいものはどれか。",
        "question_type": "single",
        "choices": [
            "P(B|A) P(A) / P(B)",
            "P(A) P(B) / P(A∩B)",
            "P(A) + P(B) - P(A∩B)",
            "P(A∩B) / (P(A) + P(B))",
        ],
        "correct_answer": 0,
        "explanation": "ベイズの定理: P(A|B) = P(B|A) P(A) / P(B)。事前確率 P(A) と尤度 P(B|A) から事後確率を求める。スパムフィルタや診断 AI の基礎。",
        "difficulty": 2,
        "tags": ["統計", "ベイズの定理"],
    },
    {
        "syllabus_category": "数学基礎",
        "subcategory": "確率・統計",
        "question_text": "仮説検定における「第1種の過誤 (Type I error)」とは何か。",
        "question_type": "single",
        "choices": [
            "帰無仮説が正しいのに棄却してしまう (False Positive)",
            "帰無仮説が誤りなのに棄却しない (False Negative)",
            "データに欠損値が多い",
            "サンプルサイズが不足している",
        ],
        "correct_answer": 0,
        "explanation": "第1種の過誤は α (有意水準) で制御。第2種の過誤 β (False Negative) は検出力 1-β と対応する。両者はトレードオフ関係にある。",
        "difficulty": 2,
        "tags": ["統計", "仮説検定"],
    },
    {
        "syllabus_category": "数学基礎",
        "subcategory": "確率・統計",
        "question_text": "中心極限定理によれば、独立同分布の確率変数を多数足し合わせた和 (または平均) は近似的に正規分布に従う。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "元の分布の形に依らず、サンプル数を増やすほど標本平均の分布は正規分布に近づく (条件: 分散が有限)。統計学・機械学習の基礎。",
        "difficulty": 1,
        "tags": ["統計", "中心極限定理"],
    },
    {
        "syllabus_category": "数学基礎",
        "subcategory": "確率・統計",
        "question_text": "正規分布 (ガウス分布) を一意に決めるパラメータの組み合わせとして正しいものはどれか。",
        "question_type": "single",
        "choices": [
            "平均と標準偏差 (分散)",
            "最大値と最小値",
            "中央値と四分位範囲",
            "歪度と尖度",
        ],
        "correct_answer": 0,
        "explanation": "1次元正規分布 N(μ, σ²) は平均 μ と分散 σ² で完全に定まる。多次元では平均ベクトルと共分散行列で表現する。",
        "difficulty": 1,
        "tags": ["統計", "正規分布"],
    },
    {
        "syllabus_category": "数学基礎",
        "subcategory": "確率・統計",
        "question_text": "クロスエントロピー誤差が最もよく使われる機械学習タスクはどれか。",
        "question_type": "single",
        "choices": [
            "回帰問題",
            "分類問題 (ロジスティック回帰、ニューラル分類)",
            "強化学習の方策学習",
            "クラスタリング",
        ],
        "correct_answer": 1,
        "explanation": "予測確率分布と真の分布の差を測る。2クラス分類なら Binary CE、多クラスなら Categorical CE が標準。",
        "difficulty": 2,
        "tags": ["統計", "クロスエントロピー"],
    },
    {
        "syllabus_category": "数学基礎",
        "subcategory": "確率・統計",
        "question_text": "「相関がある = 因果関係がある」と判断してよい。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": False,
        "explanation": "相関と因果は別概念。第3変数 (交絡因子) や偶然による擬似相関の可能性がある。「アイスクリーム売上と水難事故」は「気温」を媒介する典型例。",
        "difficulty": 1,
        "tags": ["統計", "相関と因果"],
    },
    # ========== 数学基礎 / 線形代数 ==========
    {
        "syllabus_category": "数学基礎",
        "subcategory": "線形代数",
        "question_text": "ベクトル x = (3, 4) の L2 ノルム (ユークリッドノルム) はいくつか。",
        "question_type": "single",
        "choices": ["5", "7", "12", "25"],
        "correct_answer": 0,
        "explanation": "L2 ノルム = √(3² + 4²) = √25 = 5。L1 ノルムなら |3| + |4| = 7、L∞ ノルムなら max(|3|, |4|) = 4。",
        "difficulty": 1,
        "tags": ["線形代数", "ノルム"],
    },
    {
        "syllabus_category": "数学基礎",
        "subcategory": "線形代数",
        "question_text": "コサイン類似度 cos(x, y) の値域として正しいものはどれか。",
        "question_type": "single",
        "choices": ["[0, 1]", "[-1, 1]", "[0, ∞)", "(-∞, ∞)"],
        "correct_answer": 1,
        "explanation": "cos(x, y) = (x·y) / (||x|| ||y||)。同じ方向なら 1、直交で 0、逆方向なら -1。文書・埋め込みベクトル類似度で頻用。",
        "difficulty": 1,
        "tags": ["線形代数", "コサイン類似度"],
    },
    {
        "syllabus_category": "数学基礎",
        "subcategory": "線形代数",
        "question_text": "行列 A の固有値・固有ベクトルの定義として正しいものはどれか。",
        "question_type": "single",
        "choices": [
            "Av = λv を満たす λ (固有値) と非零ベクトル v (固有ベクトル)",
            "A + B = I を満たす λ と v",
            "AB = BA を満たす λ と v",
            "det(A) = 0 を満たす λ と v",
        ],
        "correct_answer": 0,
        "explanation": "行列 A をかけても向きが変わらず λ 倍だけスケーリングされる特別なベクトル v とその係数 λ。PCA, ページランク等の基礎。",
        "difficulty": 2,
        "tags": ["線形代数", "固有値"],
    },
    {
        "syllabus_category": "数学基礎",
        "subcategory": "線形代数",
        "question_text": "特異値分解 (SVD) の代表的応用として最も適切なものはどれか。",
        "question_type": "single",
        "choices": [
            "次元削減・推薦システム・画像圧縮",
            "活性化関数の選択",
            "強化学習の報酬設計",
            "GAN の Generator 設計",
        ],
        "correct_answer": 0,
        "explanation": "SVD は任意の行列を U Σ Vᵀ に分解。Truncated SVD で次元削減、行列分解で推薦システム、主要特異値だけで画像圧縮等に応用。",
        "difficulty": 2,
        "tags": ["線形代数", "SVD"],
    },
    {
        "syllabus_category": "数学基礎",
        "subcategory": "線形代数",
        "question_text": "主成分分析 (PCA) はデータの共分散行列の固有値分解を用いて分散が最大となる方向 (主成分) を求める手法である。",
        "question_type": "true_false",
        "choices": [],
        "correct_answer": True,
        "explanation": "共分散行列の固有ベクトルが主成分方向、対応する固有値が分散の大きさ。寄与率の高い主成分だけ残すことで次元削減できる。",
        "difficulty": 2,
        "tags": ["線形代数", "PCA"],
    },
]
